import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import {
  OrganizationSwitcher,
  SignedIn,
  UserButton,
} from "@neondatabase/neon-js/auth/react/ui";

import { AuthProvider } from "@/components/auth-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SignedIn>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <UserButton size="icon" />
              <OrganizationSwitcher hidePersonal />
            </header>
          </SignedIn>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
