const DEFAULT_COUNTY_PARAM = "hele-landet";
const DEFAULT_ORGANIZATION_PARAM = "alle";
const DEFAULT_GROUP_PARAM = "organisasjoner";

module.exports = {
  DEFAULT_COUNTY_PARAM,
  DEFAULT_ORGANIZATION_PARAM,
  DEFAULT_GROUP_PARAM,
};
